--max_cycles=99999 # "--setting" here is equivalent to "setting"
max_heap=64MB # "max_heap = 64MB", "max_heap= 64 MB", for example, are also valid
 max_stack=8MB
ram_size = 256MB
out=default
in=default
--args=1 2 3
#config, help, disclaimer, and target are invalid options in a config file

# 1. everything after the first hash symbol on a line is treated as a comment and ignored
# 2. everything after the first "equals" symbol on a line is trimmed and treated as a value