--max_cycles=99999 # "--setting" here is equivalent to "setting"
max_heap=64MB # "max_heap = 64MB", "max_heap= 64 MB", for example, are also valid
max_stack=8MB
stdout=default
stdin=default
--args="1 2 3"
#config, help, disclaimer, and target are invalid options in a config file